services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      - ./backend/service-account.json:/app/service-account.json
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
